coverage:
  status:
    project:
      default:
        # We want to always increase project code coverage until we reach a good
        # point (~80%)
        target: auto
        threshold: 0%

    patch:
      default:
        # if we want to reach more coverage with time, we must enforce new code
        # comes tested
        target: 75%

ignore:
  - "**/tests/**"
