name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        GA_TESTING_SERVICE_TOKEN: ${{ secrets.GA_TESTING_SERVICE_TOKEN }}
        GA_TESTING_TOKEN: ${{ secrets.GA_TESTING_TOKEN }}
        STAGE_TESTING_SERVICE_TOKEN: ${{ secrets.STAGE_TESTING_SERVICE_TOKEN }}
        STAGE_TESTING_TOKEN: ${{ secrets.STAGE_TESTING_TOKEN }}
        TEST_EUROPE1_STASHIFY_NUA: ${{ secrets.TEST_EUROPE1_STASHIFY_NUA }}
      run: |
        echo $GA_TESTING_SERVICE_TOKEN >> secrets.txt
        echo $GA_TESTING_TOKEN >> secrets.txt
        echo $STAGE_TESTING_SERVICE_TOKEN >> secrets.txt
        echo $STAGE_TESTING_TOKEN >> secrets.txt
        echo $TEST_EUROPE1_STASHIFY_NUA >> secrets.txt
    - name: Run tmate
      uses: mxschmitt/action-tmate@v2