name: Push docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  publish-doc:
    name: Publish documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: '${{ secrets.AWS_DOCS_SYNC_ROLE }}'
          aws-region: ${{ secrets.AWS_DOCS_SYNC_REGION }}

      - name: Push SDK docs to S3
        run: aws s3 sync ./docs s3://${{ secrets.DOCS_STORAGE }}/python-sdk
