name: Nuclia SDK

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install package
        run: make install

      - name: Run pre-checks
        run: make lint

      - name: Test
        run: GA_TESTING_SERVICE_TOKEN="${{ secrets.GA_TESTING_SERVICE_TOKEN }}" GA_TESTING_NUA="${{ secrets.GA_TESTING_NUA }}" make test
