name: PyPI Releases

on:
  push:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup env
        run: |
          pip install wheel
          pip install -U twine

      # Install all packages we are going to release
      - name: Install all packages
        run: |
          pip install -e .

      - name: Build wheels
        run: pip wheel --no-deps -w dist .

      # XXX wait for tests to run successfully in all dependencies before we actually release
      - name: Wait for Tests
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: main
          check-name: Nuclia SDK
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Upload to pypi
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
